---
# tasks file for roles/rsyslog

- name: Install rsyslog
  dnf:
    name: rsyslog
    state: present

- name: Enable rsyslog
  service:
    name: rsyslog
    state: started
    enabled: yes

- name: Configure remote logging
  copy:
    dest: /etc/rsyslog.d/remote.conf
    content: |
      *.* @@172.31.42.88:514

- name: Restart rsyslog
  service:
    name: rsyslog
    state: restarted
