---
# tasks file for roles/security

- name: Install firewalld
  dnf:
    name: firewalld
    state: present

- name: Install python3-firewall
  dnf:
    name: python3-firewall
    state: present

- name: Enable firewalld
  service:
    name: firewalld
    enabled: yes
    state: started

- name: Allow HTTP
  ansible.posix.firewalld:
    service: http
    permanent: true
    state: enabled
    immediate: true

- name: Allow SSH
  ansible.posix.firewalld:
    service: ssh
    permanent: true
    state: enabled
    immediate: true
